@
_HostAddress = http://localhost:5085

GET {{SupermarketCheckout_HostAddress}}/checkout
Accept: application/json

###

GET {{SupermarketCheckout_HostAddress}}/checkout/A
Accept: application/json

###

POST {{SupermarketCheckout_HostAddress}}/checkout/ABCD
Accept: application/json

###
